
ALTER TABLE OA_NOTIFY ADD REMIND_DATE TIMESTAMP;
ALTER TABLE OA_NOTIFY ADD READ_FLAG CHAR(1);

ALTER TABLE gen_table ADD DB_SCHEMA VARCHAR2(32);

ALTER TABLE sys_area add REGION      VARCHAR2(64);
ALTER TABLE sys_area add LONGITUDE   VARCHAR2(20);
ALTER TABLE sys_area add LATITUDE    VARCHAR2(20);